url: https://nonusingh.github.io
baseurl: 

# Site settings
title: Nonu Singh
email: nonuatamd@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
#people:
#- name: Python Projects
#  pic: 1
#  position: Lead Designer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

#- name: Udacity Nanodegree
#  pic: 2
#  position: Lead Marketer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #

#- name: Other Projects
#  pic: 3
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin 
    url: http://www.linkedin.com/in/nonusingh
  - title: github
    url: https://github.com/nonusingh

# Postal address (add as many lines as necessary)
address:
#  - line: 3481 Melrose Place
  - line: Clifton Park, NY 12065

# Build settings
markdown: kramdown
permalink: pretty
